name: GitHub Wiki Action
description: 🔗 Rewrite links and file names to work better with GitHub wikis

branding:
  icon: link
  color: blue

inputs:
  path:
    default: .

runs:
  using: composite
  steps:
    - id: main
      run: '"${GITHUB_ACTION_PATH%/}/mainw"'
      shell: bash
      env:
        INPUT_PATH: ${{ inputs.path }}
