name: GitHub Wiki Action
description: 🔗 Rewrite links and file names to work better with GitHub wikis

branding:
  icon: link
  color: blue

inputs:
  path:
    default: wiki

runs:
  using: node20
  main: _main.mjs #=> main.ts
