name: Test reverse action
on:
  push:
    branches: "main"
    paths:
      - reverse/**
      - "!reverse/LICENSE"
      - "!reverse/README.md"
      - .github/workflows/test-reverse-action.yml
  pull_request:
    paths:
      - reverse/**
      - "!reverse/LICENSE"
      - "!reverse/README.md"
      - .github/workflows/test-reverse-action.yml
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  test-reverse-action:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./reverse
        with:
          path: reverse/test
      - run: cat reverse/test/README.md
