name: Test reverse action
on:
  push:
    branches: "main"
    paths:
      - reverse/**
      - "!reverse/LICENSE"
      - "!reverse/README.md"
      - .github/workflows/test-reverse-action.yml
  pull_request:
    paths:
      - reverse/**
      - "!reverse/LICENSE"
      - "!reverse/README.md"
      - .github/workflows/test-reverse-action.yml
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  test-reverse-action:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
      - run: npm ci
      - run: npm run -w ./reverse build
      - uses: ./reverse
        with:
          path: test
