name: Test action
on:
  push:
    branches: "main"
    paths:
      - infer-link-exts/**
      - "!infer-link-exts/LICENSE"
      - "!infer-link-exts/README.md"
      - .github/workflows/test-action.yml
  pull_request:
    paths:
      - infer-link-exts/**
      - "!infer-link-exts/LICENSE"
      - "!infer-link-exts/README.md"
      - .github/workflows/test-action.yml
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  path:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          path: test
      - run: cat test/README.md
